package com.jointem.dbhelper;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.jointem.dbhelper.AreaCity;
import com.jointem.dbhelper.Categories;
import com.jointem.dbhelper.CityStationBean;
import com.jointem.dbhelper.DownInfo;
import com.jointem.dbhelper.Press;
import com.jointem.dbhelper.SearchRecord;
import com.jointem.dbhelper.Site;
import com.jointem.dbhelper.StationsHistory;
import com.jointem.dbhelper.UserInfo;

import com.jointem.dbhelper.AreaCityDao;
import com.jointem.dbhelper.CategoriesDao;
import com.jointem.dbhelper.CityStationBeanDao;
import com.jointem.dbhelper.DownInfoDao;
import com.jointem.dbhelper.PressDao;
import com.jointem.dbhelper.SearchRecordDao;
import com.jointem.dbhelper.SiteDao;
import com.jointem.dbhelper.StationsHistoryDao;
import com.jointem.dbhelper.UserInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig areaCityDaoConfig;
    private final DaoConfig categoriesDaoConfig;
    private final DaoConfig cityStationBeanDaoConfig;
    private final DaoConfig downInfoDaoConfig;
    private final DaoConfig pressDaoConfig;
    private final DaoConfig searchRecordDaoConfig;
    private final DaoConfig siteDaoConfig;
    private final DaoConfig stationsHistoryDaoConfig;
    private final DaoConfig userInfoDaoConfig;

    private final AreaCityDao areaCityDao;
    private final CategoriesDao categoriesDao;
    private final CityStationBeanDao cityStationBeanDao;
    private final DownInfoDao downInfoDao;
    private final PressDao pressDao;
    private final SearchRecordDao searchRecordDao;
    private final SiteDao siteDao;
    private final StationsHistoryDao stationsHistoryDao;
    private final UserInfoDao userInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        areaCityDaoConfig = daoConfigMap.get(AreaCityDao.class).clone();
        areaCityDaoConfig.initIdentityScope(type);

        categoriesDaoConfig = daoConfigMap.get(CategoriesDao.class).clone();
        categoriesDaoConfig.initIdentityScope(type);

        cityStationBeanDaoConfig = daoConfigMap.get(CityStationBeanDao.class).clone();
        cityStationBeanDaoConfig.initIdentityScope(type);

        downInfoDaoConfig = daoConfigMap.get(DownInfoDao.class).clone();
        downInfoDaoConfig.initIdentityScope(type);

        pressDaoConfig = daoConfigMap.get(PressDao.class).clone();
        pressDaoConfig.initIdentityScope(type);

        searchRecordDaoConfig = daoConfigMap.get(SearchRecordDao.class).clone();
        searchRecordDaoConfig.initIdentityScope(type);

        siteDaoConfig = daoConfigMap.get(SiteDao.class).clone();
        siteDaoConfig.initIdentityScope(type);

        stationsHistoryDaoConfig = daoConfigMap.get(StationsHistoryDao.class).clone();
        stationsHistoryDaoConfig.initIdentityScope(type);

        userInfoDaoConfig = daoConfigMap.get(UserInfoDao.class).clone();
        userInfoDaoConfig.initIdentityScope(type);

        areaCityDao = new AreaCityDao(areaCityDaoConfig, this);
        categoriesDao = new CategoriesDao(categoriesDaoConfig, this);
        cityStationBeanDao = new CityStationBeanDao(cityStationBeanDaoConfig, this);
        downInfoDao = new DownInfoDao(downInfoDaoConfig, this);
        pressDao = new PressDao(pressDaoConfig, this);
        searchRecordDao = new SearchRecordDao(searchRecordDaoConfig, this);
        siteDao = new SiteDao(siteDaoConfig, this);
        stationsHistoryDao = new StationsHistoryDao(stationsHistoryDaoConfig, this);
        userInfoDao = new UserInfoDao(userInfoDaoConfig, this);

        registerDao(AreaCity.class, areaCityDao);
        registerDao(Categories.class, categoriesDao);
        registerDao(CityStationBean.class, cityStationBeanDao);
        registerDao(DownInfo.class, downInfoDao);
        registerDao(Press.class, pressDao);
        registerDao(SearchRecord.class, searchRecordDao);
        registerDao(Site.class, siteDao);
        registerDao(StationsHistory.class, stationsHistoryDao);
        registerDao(UserInfo.class, userInfoDao);
    }
    
    public void clear() {
        areaCityDaoConfig.clearIdentityScope();
        categoriesDaoConfig.clearIdentityScope();
        cityStationBeanDaoConfig.clearIdentityScope();
        downInfoDaoConfig.clearIdentityScope();
        pressDaoConfig.clearIdentityScope();
        searchRecordDaoConfig.clearIdentityScope();
        siteDaoConfig.clearIdentityScope();
        stationsHistoryDaoConfig.clearIdentityScope();
        userInfoDaoConfig.clearIdentityScope();
    }

    public AreaCityDao getAreaCityDao() {
        return areaCityDao;
    }

    public CategoriesDao getCategoriesDao() {
        return categoriesDao;
    }

    public CityStationBeanDao getCityStationBeanDao() {
        return cityStationBeanDao;
    }

    public DownInfoDao getDownInfoDao() {
        return downInfoDao;
    }

    public PressDao getPressDao() {
        return pressDao;
    }

    public SearchRecordDao getSearchRecordDao() {
        return searchRecordDao;
    }

    public SiteDao getSiteDao() {
        return siteDao;
    }

    public StationsHistoryDao getStationsHistoryDao() {
        return stationsHistoryDao;
    }

    public UserInfoDao getUserInfoDao() {
        return userInfoDao;
    }

}
